version: '3.7'

services:
 backend:
  container_name: backend-container
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - 5000:5000
  environment:
   PORT: 3000  
  depends_on:
   - database
  networks:
   - my-network

 client:
  container_name: client-container
  build:
   context: ./client
   dockerfile: Dockerfile
   
  #  volume:
  #  - mongo-volume
  #  ports:
  #   - 4000:4000
  #  networks:
  #  - my-network
 
 database:
  container_name: 'mongodb-database'
  image: mongo
  environment:
      - MONGO_INITDB_ROOT_USERNAME=root1
      - MONGO_INITDB_ROOT_PASSWORD=password
  ports:
      - 27018:27018
  volumes:
      - mongo-volume:/data/db
  networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  mongo-volume: